import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import ToasterProvider from "@/Components/Providers/ToasterProvider";
// import Banner from "@/Components/Home/Banner/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CARE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 bg-white/70 backdrop-blur-md">
          <div className="py-2 md:w-11/12 mx-auto">
            <Navbar />
          </div>
        </header>

        <main>
          <section>{children}</section>
        </main>

        <footer>
          <Footer />
        </footer>
        <ToasterProvider />
      </body>
    </html>
  );
}
